import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const timesTen = localFont({
  src: [
    {
      path: "../../public/fonts/TimesTen.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-times-ten",
});

const helvetica = localFont({
  src: [
    {
      path: "../../public/fonts/Helvetica.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${timesTen.variable} ${helvetica.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
